spring:
  datasource:
    url: jdbc:h2:./db_test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  site:
    baseUrl: "http://localhost:8090"
  tempDirPath: c:/temp/flow_test/temp
  genFile:
    dirPath: c:/temp/flow_test